Repository MARIMO-PROJECT/MARIMO-CLIENT, pull requests merged in 2025-04, with the labels that each got.

#2 [Init/#1] 초기세팅
  .gitignore
  .svgrrc
  README.md
  eslint.config.js
  eslint.config.mjs
  index.html
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/fonts/PretendardVariable.woff2
  public/fonts/SUIT-Variable.woff2
  public/images/.keep
  public/svgs/.keep
  public/vite.svg
  src/App.css
  src/App.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/react.svg
  src/components/.keep
  src/hooks/.keep
  src/index.css
  src/main.tsx
  src/styles/.keep
  src/styles/generator.css.ts
  src/styles/global.css.ts
  src/styles/layers.css.ts
  src/styles/reset.css.ts
  src/styles/theme.css.ts
  src/types/.keep
  src/utils/.keep
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: Init, 🐻 Chaeneey

#6 [Feat/#5] Chip 컴포넌트 구현
  .github/ISSUE_TEMPLATE/🌸기능-추가.md
  .github/ISSUE_TEMPLATE/🌼버그-추가.md
  src/components/.keep
  src/components/Chip/Chip.css.ts
  src/components/Chip/Chip.tsx
  src/components/index.ts
  src/styles/theme.css.ts
  tsconfig.json
Labels: Feat, 🐧 Hwarang

#16 [Init/#15] caption 폰트 추가
  src/styles/theme.css.ts
Labels: Init, 🐻 Chaeneey

#8 [Feat/#7] CustomImage컴포넌트 구현
  src/components/CustomImage/CustomImage.css.ts
  src/components/CustomImage/CustomImage.tsx
  src/components/index.ts
Labels: Feat, 🐧 Hwarang

#10 [Feat/#9] IUButton 컴포넌트 구현
  src/components/IUButton/IUButton.css.ts
  src/components/IUButton/IUButton.tsx
  src/components/index.ts
Labels: Feat, 🐧 Hwarang

#19 [Feat/#18] Footer 컴포넌트 구현
  public/svgs/ic_instagram.svg
  public/svgs/ic_kakao.svg
  src/assets/svgs/IcInstagram.tsx
  src/assets/svgs/IcKakao.tsx
  src/assets/svgs/index.ts
  src/components/Footer/Footer.css.ts
  src/components/Footer/Footer.tsx
Labels: Feat, 🐧 Hwarang

#22 [Feat/#20] TabBar 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/TabBar/TabBar.css.ts
  src/components/TabBar/TabBar.tsx
  src/components/index.ts
  src/styles/theme.css.ts
Labels: Feat, 🐧 Hwarang

#24 [Feat/#14] Input, TextArea 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  public/svgs/ic_btn_delete.svg
  src/assets/svgs/IcBtnDelete.tsx
  src/assets/svgs/index.ts
  src/components/Input/Input.css.ts
  src/components/Input/Input.tsx
  src/components/TextArea/TextArea.css.ts
  src/components/TextArea/TextArea.tsx
Labels: Feat, 🐻 Chaeneey

#17 [Feat/#13] Accordion 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  public/svgs/ic_arrow_under_gray05_34.svg
  src/assets/svgs/IcArrowUnderGray0534.tsx
  src/assets/svgs/index.ts
  src/components/Accordion/Accordion.css.ts
  src/components/Accordion/Accordion.tsx
  src/components/index.ts
Labels: Feat, 🐧 Hwarang

#26 [Feat/#25] Header 컴포넌트 구현 완료
  src/assets/svgs/index.ts
  src/components/Button/Button.css.ts
  src/components/Button/Button.tsx
  src/components/Header/Header.css.ts
  src/components/Header/Header.tsx
  src/components/index.ts
Labels: Feat, 🐧 Hwarang

#29 [Feat/#27] 레이아웃 설정 & header,footer 수정
  public/svgs/ic_insta.svg
  public/svgs/ic_instagram.svg
  public/svgs/ic_kakao.svg
  src/app/(common)/invitation/detail/[id]/page.tsx
  src/app/(common)/layout.tsx
  src/assets/svgs/IcInsta.tsx
  src/assets/svgs/IcInstagram.tsx
  src/assets/svgs/IcKakao.tsx
  src/assets/svgs/index.ts
  src/components/Footer/Footer.css.ts
  src/components/Footer/Footer.tsx
  src/components/Header/Header.css.ts
Labels: Fix, Feat, 🐧 Hwarang
